name: Build

env:
  include_paths: |
              charsets/
              docs/
              extra/
              layouts/
              masks/
              modules/
              OpenCL/
              rules/
              example*
              hashcat*

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # todo: windows-latest - lack of iconv development files
        shared: [0, 1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          SHARED: ${{ matrix.shared }}
        run: make
      - name: Generate artifacts (shared)
        uses: actions/upload-artifact@v3
        with:
          name: hashcat-${{ matrix.os }}-${{ matrix.shared }}
          path: ${{ env.include_paths }}
